### ISSUE TITLE
Long time no see.... I've update the Chinese Doc

### ISSUE THREAD

**Issue by vrbvillor** [shakiba/stage.js#31]
Because the changes between the old version and the new one are too disperse and too many, and I can't delete the old one. Well please change the Chinese Doc link in your English one to the new Chinese Doc. And I found a omission that at the end of **Global Methods** , the second section 

```javascript
// Create and preload a texture atlas
Stage({ });
```

the parameter has nothing as its key or value. Is it right?

Glad to interrupt you. Hahahahah                               Villor

**Comment by shakiba** [comment]
Thanks, that's great! Can you please replace the old page with new one (just copy content of new page to the old page)? Because two pages can be confusing.

Yes, it assumes key-values which are explained in "Texture Atlas" section.

**Comment by vrbvillor** [comment]
I've copied the new content into the old one.

**Comment by shakiba** [comment]
Thank you! :)
