### ISSUE TITLE
await is a reserved word (991:5)

### ISSUE THREAD

**Issue by showzyl** [shakiba/stage.js#32]
when i use gulp-babel to compile my project, thers is an error message blew, could u please fixd this issue?

message: /Users/showzyl/Desktop/workspace/hybird/dsp/src/js/stage.js: await is a reserved word (991:5)

**Comment by shakiba** [comment]
I will fix it.

**Comment by shakiba** [comment]
I will fix it, however if you are interested to fix it quickly you are welcome to make a PR. Just change [variables](https://github.com/shakiba/stage.js/search?utf8=%E2%9C%93&q=await) with `await` name to `_await`, increase build version in `package.js` and build it (`npm run dist`).

**Comment by shakiba** [comment]
Fixed.
