### ISSUE TITLE
What application are the texture atlases created in?

### ISSUE THREAD

**Issue by nureyev** [shakiba/stage.js#33]
I was wondering what application the texture atlas .js was being created in? 

Thanks.

**Comment by shakiba** [comment]
They are created manually, but if you use an app, probably you can easily convert its definition file to stage.js expected format.

**Comment by nureyev** [comment]
I checked all the texture.js files in the examples, so I think I know what the format looks like. Is there a full specification somewhere? 

I'll try later with Shoebox (http://renderhjs.net/shoebox/).

**Comment by shakiba** [comment]
No, but [this example](https://github.com/shakiba/stage.js#texture-atlas) covers most of supported cases.

**Comment by nureyev** [comment]
Thanks. I'll try to write the export expression later today or tomorrow for Shoebox.

**Comment by shakiba** [comment]
You are welcome! Let me know if you have any other question!
