### ISSUE TITLE
Is there a way of mounting the app in a custom node?

### ISSUE THREAD

**Issue by alexfertel** [shakiba/stage.js#41]
I couldn't find anywhere how to mount the app in a custom node. I would like to integrate `stagejs` with `vuejs` to make a domino game.

**Comment by shakiba** [comment]
This should work: `Stage(callback, {canvas: idOrDom});`

**Comment by alexfertel** [comment]
Thx for the quick answer, but my problem remains.

This creates a `canvas` element as a child of `body` as if I didn't specify anything.

**Comment by shakiba** [comment]
It needs to be an existing canvas element or its id, see [here](https://github.com/shakiba/stage.js/blob/master/lib/loader/web.js#L28).

**Comment by alexfertel** [comment]
Thx, I was trying to mount it on a `div` element. Sorry for the trouble!

**Comment by shakiba** [comment]
No problem! :)
