### ISSUE TITLE
Should Tween._done be a list?

### ISSUE THREAD

**Issue by tianzhuqiao** [shakiba/stage.js#43]
Thanks for the great project, @shakiba. Currently **Tween._done** supports one function. Should we make it a list, such that the following application will also work?
`img.tween(100).alpha(0).remove().done(fn)`

Otherwise, it will fail to **remove** since 
1. **remove**() set **_done** to **this.remove()**,
2. but **done(fn)** will overwrite the **_done**. to **fn**.

**Comment by shakiba** [comment]
Hmm, yes that doesn't look good. I'm not sure if we should queue or replace multiple "done", but remove and done should be separated. Would you be able to make a PR to fix it!

**Comment by tianzhuqiao** [comment]
Yeah, separate **remove()** and **hide()** from **done()** is a good idea.
